#!/bin/bash

id

wget -q https://www.mathworks.com/mpm/glnxa64/mpm
chmod +x mpm

MATLAB_RELEASE=r2023b
MATLAB_INSTALL_LOCATION=${HOME}/.local/mathworks/matlab/${MATLAB_RELEASE}
MATLAB_PRODUCT_LIST=MATLAB

mkdir -p ${MATLAB_INSTALL_LOCATION}

./mpm install \
    --release=${MATLAB_RELEASE} \
    --destination=${MATLAB_INSTALL_LOCATION} \
    --products ${MATLAB_PRODUCT_LIST} \
    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false)

rm -f mpm /tmp/mathworks_root.log

ln -s ${MATLAB_INSTALL_LOCATION}/bin/matlab ${HOME}/.local/bin/matlab