#!/bin/bash

id

wget -q https://www.mathworks.com/mpm/glnxa64/mpm
chmod +x mpm

MATLAB_RELEASE=r2023b
MATLAB_INSTALL_LOCATION=${HOME}/.local/matlab
MATLAB_PRODUCT_LIST=MATLAB

mkdir -p ${MATLAB_INSTALL_LOCATION}

./mpm install \
    --release=${MATLAB_RELEASE} \
    --destination=${MATLAB_INSTALL_LOCATION} \
    --products ${MATLAB_PRODUCT_LIST} \
    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_$(id -un).log && false)

ls ${MATLAB_INSTALL_LOCATION}

ls /tmp

rm -f mpm /tmp/mathworks_$(id -un).log

mkdir -p ${HOME}/.local/bin
ln -s ${MATLAB_INSTALL_LOCATION}/bin/matlab ${HOME}/.local/bin/matlab
